on:
  workflow_dispatch:
  #pull_request_target:
    #types:
      #- closed

jobs:
  if_merged:
    #if: github.event.pull_request.merged == true
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run a script
        run: ./createTimelines.vbs
